// Embedded ONLYOFFICE Docs editor.
//
// The full config (including the server-signed JWT) is generated by the backend
// — the browser never signs anything. We only load the Document Server's api.js
// and mount the editor with that config.
import { useEffect, useRef } from "react";

let apiScriptPromise = null;

function loadDocsApi(apiJsUrl) {
  if (window.DocsAPI) return Promise.resolve();
  if (apiScriptPromise) return apiScriptPromise;
  apiScriptPromise = new Promise((resolve, reject) => {
    const script = document.createElement("script");
    script.src = apiJsUrl;
    script.async = true;
    script.onload = () => resolve();
    script.onerror = () => {
      apiScriptPromise = null;
      reject(new Error("Could not load the ONLYOFFICE editor. Is the Document Server running?"));
    };
    document.body.appendChild(script);
  });
  return apiScriptPromise;
}

export default function OnlyOfficeEditor({
  apiJsUrl,
  config,
  onDirtyChange,
  onError,
  onReady,
}) {
  const containerRef = useRef(null);
  const editorRef = useRef(null);
  const callbacksRef = useRef({ onDirtyChange, onError, onReady });

  useEffect(() => {
    callbacksRef.current = { onDirtyChange, onError, onReady };
  }, [onDirtyChange, onError, onReady]);

  useEffect(() => {
    let cancelled = false;
    loadDocsApi(apiJsUrl)
      .then(() => {
        if (cancelled || !containerRef.current || !window.DocsAPI) return;
        const merged = {
          ...config,
          events: {
            ...(config.events || {}),
            onDocumentReady: (event) => {
              config.events?.onDocumentReady?.(event);
              callbacksRef.current.onReady?.();
            },
            onDocumentStateChange: (event) => {
              config.events?.onDocumentStateChange?.(event);
              callbacksRef.current.onDirtyChange?.(Boolean(event?.data));
            },
            onError: (event) => {
              config.events?.onError?.(event);
              const data = event?.data || {};
              callbacksRef.current.onError?.(
                new Error(data.errorDescription || "ONLYOFFICE reported an editor error.")
              );
            },
          },
        };
        editorRef.current = new window.DocsAPI.DocEditor(containerRef.current.id, merged);
      })
      .catch((err) => callbacksRef.current.onError?.(err));

    return () => {
      cancelled = true;
      try {
        editorRef.current?.destroyEditor?.();
      } catch {
        /* editor already torn down */
      }
      editorRef.current = null;
      callbacksRef.current.onReady?.(false);
    };
  }, [apiJsUrl, config]);

  // A stable, unique container id for this mount.
  const idRef = useRef(`onlyoffice-${Math.random().toString(36).slice(2)}`);
  return (
    <div className="onlyoffice-shell">
      <div id={idRef.current} ref={containerRef} className="onlyoffice-mount" />
    </div>
  );
}
